# ----------- Information -----------

# Author: Echo24h
# This plugin is licensed

# Plugin Page : https://www.spigotmc.org/resources/chatformatting-premium-1-13-x-1-20-x.110976/

# Source Code: https://github.com/Echo24h/ChatFormatting-Premium

# Author Page: https://www.spigotmc.org/members/echo24h.1711225/

# Discord: https://discord.com/invite/Xf3PjwXzKg

# Donation Link: https://www.paypal.com/donate/?hosted_button_id=J4Y27JYWLYLBG

# ----------- Config -----------

# Replacement text for clickable links
replacement-of-link: '&l&n&o&bLINK'

# Replacement text for item in chat (use [item] for put your hand item in chat)
# - {name}: Replaced with the name of item
replacement-of-item: '&o&7[&e{name}&7]'

# Replacement text for mention
# - {name}: Replaced with the targeted player name or 'everyone'
replacement-of-mention: '&b&o@{name}'

# Activates a small sound when sending/receiving player chats
chat-notification-sound: true

# Activates a sound when receiving mention
mention-notification-sound: true